### ISSUE TITLE
The blue paragraph is not blue

### ISSUE THREAD

**Issue by maxbycode** [maxbycodeorg/alfonso#1]
![bluepg](https://cloud.githubusercontent.com/assets/11779550/25662381/8bbbc310-2fd1-11e7-83e9-bae2bde86f43.PNG)
[At line 30](https://github.com/maxbycodeorg/alfonso/blob/master/website1.html#L30)

**Comment by R4nd0mP0t4t021** [comment]
fuck you little bitch

**Comment by R4nd0mP0t4t021** [comment]
I will go to your house, and rape your DOOOOOOOOG
